[project]
name = "attribute-lark"
version = "0.1.0"
license = {text = "MIT"}
description = "LALR(1) attribute parser"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["interegular>=0.3.1,<0.4.0"]
